name: 'Start Runner'
description: 'Start or stop a Dockerized GitHub runner'
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/start_runner.sh ${{ inputs.command }}
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        UUID: ${{ inputs.UUID }}

inputs:
  command:
    description: 'Command to execute (start or stop)'
    required: true
  UUID:
    description: 'Unique identifier for the runner'
    required: true
  ACCESS_TOKEN:
    description: 'GitHub Runner access token'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access Key ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret Access Key'
    required: true
