name: 'Start Runner'
description: 'Start or stop a Dockerized GitHub runner'
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/start_runner.sh ${{ inputs.command }}
      shell: bash
      env:
        ACCESS_TOKEN: ${{ secrets.CREATE_RUNNER_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        UUID: ${{ inputs.UUID }}

inputs:
  command:
    description: 'Command to execute (start or stop)'
    required: true
  UUID:
    description: 'Unique identifier for the runner'
    required: true
